name: digit_to_persian_word
description: Flutter package for changing digit (up to 16 digits) to the Persian word and
  add separate to an integer Convenient and practical.
version: 2.0.0
author: Resfandiari <resfandiari.dev@gamil.com>
homepage: https://github.com/resfandiari/digit_to_persian_word

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter